//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUpload
    {
        public int Fileid { get; set; }
        public byte[] Filedata { get; set; }
        public Nullable<int> TicketId { get; set; }
        public string Filetype { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string FileName { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
