//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FXTrade
    {
        public int FXTradeId { get; set; }
        public Nullable<int> FinancialEventId { get; set; }
        public Nullable<int> PortfolioId { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public Nullable<decimal> SpotForward { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string HiportRef { get; set; }
        public Nullable<int> TradeCurrencyId { get; set; }
        public Nullable<int> CounterPartyCurrencyId { get; set; }
        public string TradeNominal { get; set; }
        public string CounterPartyNominal { get; set; }
        public Nullable<int> Position { get; set; }
        public string SenderToReceieverInfo { get; set; }
        public Nullable<int> TradeAllocationFinancialEventId { get; set; }
        public Nullable<int> MatchStatusId { get; set; }
    }
}
