//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApi.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketTrackerEntities2 : DbContext
    {
        public TicketTrackerEntities2()
            : base("name=TicketTrackerEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationMaster> ApplicationMasters { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<Entity_Link> Entity_Link { get; set; }
        public virtual DbSet<Exception> Exceptions { get; set; }
        public virtual DbSet<FileUpload> FileUploads { get; set; }
        public virtual DbSet<FinancialEventSource> FinancialEventSources { get; set; }
        public virtual DbSet<FinancialEventSourceFlatFile> FinancialEventSourceFlatFiles { get; set; }
        public virtual DbSet<FinancialEventSourceSwift> FinancialEventSourceSwifts { get; set; }
        public virtual DbSet<FXTrade> FXTrades { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<ModuleMaster> ModuleMasters { get; set; }
        public virtual DbSet<PriorityMaster> PriorityMasters { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<RootCauseMaster> RootCauseMasters { get; set; }
        public virtual DbSet<StatusMaster> StatusMasters { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Trade> Trades { get; set; }
        public virtual DbSet<TradeValidationError> TradeValidationErrors { get; set; }
        public virtual DbSet<TypeMaster> TypeMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<MenuPermission> MenuPermissions { get; set; }
        public virtual DbSet<TrainingMaster> TrainingMasters { get; set; }
        public virtual DbSet<vw_user_permissions> vw_user_permissions { get; set; }
    }
}
