//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.FileUploads = new HashSet<FileUpload>();
        }
    
        public int TicketId { get; set; }
        public string Title { get; set; }
        public string TDescription { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<System.DateTime> ResponseDeadline { get; set; }
        public Nullable<System.DateTime> ResolutionDeadline { get; set; }
        public Nullable<int> RootCauseId { get; set; }
        public string Coommnets { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedon { get; set; }
    
        public virtual ApplicationMaster ApplicationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileUpload> FileUploads { get; set; }
        public virtual ModuleMaster ModuleMaster { get; set; }
        public virtual PriorityMaster PriorityMaster { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual RootCauseMaster RootCauseMaster { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
        public virtual TypeMaster TypeMaster { get; set; }
    }
}
