//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_user_permissions
    {
        public string displayname { get; set; }
        public int menuitemid { get; set; }
        public string link { get; set; }
        public Nullable<int> parentmenuid { get; set; }
        public Nullable<int> sortorder { get; set; }
        public int userid { get; set; }
        public int roleid { get; set; }
    }
}
