//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ang4api.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_Link
    {
        public int Link_ID { get; set; }
        public Nullable<int> Parent_Entity_ID { get; set; }
        public Nullable<int> Child_Entity_ID { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Entity Entity1 { get; set; }
    }
}
