//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWebapi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialEventSourceFlatFile
    {
        public int FinancialEventSourceFlatFileId { get; set; }
        public Nullable<int> FinancialEventSourceId { get; set; }
        public Nullable<int> ClientProfileId { get; set; }
        public Nullable<int> FlatFileProcessingStatusId { get; set; }
        public string FileName { get; set; }
        public string ReceiveDir { get; set; }
        public Nullable<System.DateTime> ReceiveDateTime { get; set; }
        public string ProcessingNotes { get; set; }
        public Nullable<int> LastUpdatedUser { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    
        public virtual FinancialEventSource FinancialEventSource { get; set; }
    }
}
