//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWebapi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialEventSourceSwift
    {
        public int FinancialEventSourceSwiftId { get; set; }
        public Nullable<int> FinancialEventSourceId { get; set; }
        public Nullable<int> SwiftMessageId { get; set; }
        public Nullable<int> SwiftMessageTypeId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> SenderBic { get; set; }
        public string Message { get; set; }
        public string MessageXML { get; set; }
        public Nullable<System.DateTime> ReceiveDateTime { get; set; }
    
        public virtual FinancialEventSource FinancialEventSource { get; set; }
    }
}
