//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWebapi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialEventSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialEventSource()
        {
            this.FinancialEventSourceFlatFiles = new HashSet<FinancialEventSourceFlatFile>();
            this.FinancialEventSourceSwifts = new HashSet<FinancialEventSourceSwift>();
        }
    
        public int FinancialEventSourceId { get; set; }
        public Nullable<int> FinancialEventSourceTypeId { get; set; }
        public Nullable<System.DateTime> CaptureDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialEventSourceFlatFile> FinancialEventSourceFlatFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialEventSourceSwift> FinancialEventSourceSwifts { get; set; }
    }
}
